from datetime import timedelta

from lib.unit_float import UnitFloat

SIDERISCHER_WINKELGESCHWINDIGKEIT_GRAD_PRO_TAG = UnitFloat(360 / 365.2422, '°/d')
SIDERISCHER_WINKELGESCHWINDIGKEIT_GRAD_PRO_STUNDE = UnitFloat(
    (360 + SIDERISCHER_WINKELGESCHWINDIGKEIT_GRAD_PRO_TAG) / 24, '°/h'
)
SIDERISCHER_TAG = timedelta(hours=360 / SIDERISCHER_WINKELGESCHWINDIGKEIT_GRAD_PRO_STUNDE)
ERDE_GEO = UnitFloat(35_786, 'km')
